Massive changes to scripts, added unit tests for (almost all) scripts, plus a few tweaks to configuration,

diff --git a/script/retransfer_images b/script/retransfer_images
--- a/script/retransfer_images
+++ b/script/retransfer_images
@@ -1,85 +1,47 @@
 #!/bin/bash
+#
+#  Re-transfer any images that haven't transferred correctly yet.
+#
+################################################################################
+set -e
 
-server=cdmr@digitalmycology.com:images.digitalmycology.com
-images=public/images
+source $(dirname "$0")/bash_include
 
-db_config=config/database.yml
-username=`grep -A 20 production: $db_config | grep username: | head -1 | sed "s/.*: *//"`
-database=`grep -A 20 production: $db_config | grep database: | head -1 | sed "s/.*: *//"`
-password=`grep -A 20 production: $db_config | grep password: | head -1 | sed "s/.*: *//"`
+images_root=$( rails_constant LOCAL_IMAGE_FILES )
 
-path=(. /bin /usr/bin /usr/local/bin)
+if [[ $1 == "-h" || $1 == "--help" ]]; then cat <<END; exit 1; fi
 
-if [[ $RAILS_ENV == "production" ]]; then
-  production=1
-else
-  production=0
-fi
+USAGE
+  script/retransfer_images
 
-# ----------------------------
-#  Help message.
-# ----------------------------
+DESCRIPTION
+  This is used by the webserver to try to re-transfer images which failed to
+  transfer when script/process_image ran.  It sets the "transferred" bit in
+  the images database table if successful.  It aborts at the first sign of
+  any trouble.
 
-if [[ $1 == "-h" || $1 == "--help" ]]; then cat <<-EOH; exit -1
-
-	USAGE:
-	    script/retransfer_images
-
-	DESCRIPTION:
-	    This is used by the webserver to try to re-transfer images which failed to
-	    transfer when script/process_image ran.  It sets the "transferred" bit in
-	    the images database table if successful.  It aborts at the first sign of
-	    any trouble. 
-
-	EOH
-fi
-
-# ----------------------------
-#  Subroutines.
-# ----------------------------
-
-function wait_for() {
-  while (ps -e | grep " $*\$" > /dev/null); do sleep 5; done
-}
-
-function run() {
-  if !( $* ); then
-    exit 1
-  fi
-}
-
-function run_mysql() {
-  if !( mysql -q -u "$username" -p"$password" "$database" -e "$*" ); then
-    echo "*** Failed to update database! ***"
-    exit 1
-  fi
-}
-
-# ----------------------------
-#  Main program.
-# ----------------------------
+END
 
 # Get list of images that still need to go.
-ids=`mysql -q -u "$username" -p"$password" "$database" -e "SELECT id FROM images WHERE transferred=FALSE;" | grep -v id`
-if [[ $ids == "" ]]; then
-  exit 0
-fi
+ids=$( run_mysql "SELECT id FROM images WHERE transferred=FALSE" )
+[[ $ids = "" ]] && exit 0
 
 # Transfer images.
-for id in $ids
-do
-  # Assume update_images has done our job for us if the files are missing.
-  if [[ -e $images/320/$id.jpg ]]; then
-    wait_for scp
-    run scp $images/320/$id.jpg  $server/320
-    run scp $images/640/$id.jpg  $server/640
-    run scp $images/960/$id.jpg  $server/960
-    run scp $images/1280/$id.jpg $server/1280
-    run scp $images/orig/$id.*   $server/orig
-  fi
+for id in $ids; do
+  # Assume verify_images has done our job for us if any files are missing.
+  for dir in {thumb,320,640,960,1280,orig}; do
+    for file in $images_root/$dir/$id.*; do
+      if [[ -e $file ]]; then
+        wait_for scp
+        for server in ${image_servers[@]}; do
+          scp $file $server/$dir/ || die "Failed to transfer $file to $server/$dir/."
+        done
+      fi
+    done
+  done
 
   # Update database to say that image has transferred successfully.
-  run_mysql "UPDATE images SET transferred=TRUE WHERE id=$id"
+  run_mysql "UPDATE images SET transferred=TRUE WHERE id=$id" || warn "Failed to set transferred bit on $id."
 done
 
 exit 0
diff --git a/script/rotate_image b/script/rotate_image
--- a/script/rotate_image
+++ b/script/rotate_image
@@ -1,113 +1,76 @@
 #!/bin/bash
+#
+#  Rotate and reprocess an image.
+#
+################################################################################
+set -e
 
 id=$1
 op=$2
 
-server=cdmr@digitalmycology.com:images.digitalmycology.com
-images=public/images
-orig=$images/orig/$id.jpg
+source $(dirname "$0")/bash_include
 
-db_config=config/database.yml
-username=`grep -A 20 production: $db_config | grep username: | head -1 | sed "s/.*: *//"`
-database=`grep -A 20 production: $db_config | grep database: | head -1 | sed "s/.*: *//"`
-password=`grep -A 20 production: $db_config | grep password: | head -1 | sed "s/.*: *//"`
+images_root=$( rails_constant LOCAL_IMAGE_FILES )
+orig_file=$images_root/orig/$id.jpg
 
-path=(. /bin /usr/bin /usr/local/bin)
+if [[ $1 == "-h" || $1 == "--help" ]]; then cat <<END; exit 1; fi
 
-if [[ $RAILS_ENV == "production" ]]; then
-  production=1
-else
-  production=0
-fi
+USAGE
+  script/rotate_image <id> <0|+90|-90|180|-h|-v>
 
-# ----------------------------
-#  Help message.
-# ----------------------------
+DESCRIPTION
+  This grabs the original image from the image server if it's already
+  been moved, rotates or flips the original as requested, updates the
+  database, then transfers execution to script/process_image.  It aborts at
+  the first sign of trouble. 
 
-if [[ $1 == "-h" || $1 == "--help" ]]; then cat <<-EOH; exit -1
+OPERATIONS
+  0     No transformation, just reprocess the image.
+  -90   Rotate counterclockwise 90 degrees.
+  +90   Rotate clockwise 90 degrees.
+  180   Rotate 180 degrees.
+  -h    Flip horizontally.
+  -v    Flip vertically.
 
-	USAGE:
-	    script/rotate_image [id] [0|+90|-90|180|-h|-v]
-
-	DESCRIPTION:
-	    This is designed to run on the production webserver.  It transfers the
-	    original image from the image server if it's already been moved, rotates
-	    or flips the original as requested, updates the database, then transfers
-	    execution to script/process_image.  It aborts at the first sign of
-	    trouble. 
-
-  OPERATIONS:
-      0     No transformation, just reprocess the image.
-      -90   Rotate counterclockwise 90 degrees.
-      +90   Rotate clockwise 90 degrees.
-      180   Rotate 180 degrees.
-      -h    Flip horizontally.
-      -v    Flip vertically.
-
-	EOH
-fi
-
-# ----------------------------
-#  Subroutines.
-# ----------------------------
-
-function wait_for() {
-  while (ps -e | grep " $*\$" > /dev/null); do sleep 5; done
-}
-
-function run() {
-  if !( $* ); then
-    exit 1
-  fi
-}
-
-function run_mysql() {
-  if !( mysql -q -u "$username" -p"$password" "$database" -e "$*" ); then
-    echo "*** Failed to update database! ***"
-    exit 1
-  fi
-}
-
-# ----------------------------
-#  Main program.
-# ----------------------------
+END
 
 # Get fresh copy of original image if we need to,
-if [[ ! -e $orig ]]; then
+if [[ ! -e $orig_file ]]; then
   wait_for scp
-  run scp $server/orig/$id.jpg $orig
+  server=${image_servers[0]}
+  scp $server/orig/$id.jpg $orig_file || die "Failed to grab $orig_file file from $server."
 fi
 
 # Transform image.
 wait_for "(convert|jpegresize)"
 case $op in
 "-90")
-  run convert $orig -rotate 270 $orig.new
-  run mv -f $orig.new $orig
+  convert $orig_file -rotate 270 $orig_file.new || die "Failed to rotate $orig_file."
+  mv -f $orig_file.new $orig_file               || die "Failed to move $orig_file.new into place."
   ;;
 "+90")
-  run convert $orig -rotate 90 $orig.new
-  run mv -f $orig.new $orig
+  convert $orig_file -rotate 90 $orig_file.new  || die "Failed to rotate $orig_file."
+  mv -f $orig_file.new $orig_file               || die "Failed to move $orig_file.new into place."
   ;;
 "180")
-  run convert $orig -rotate 180 $orig.new
-  run mv -f $orig.new $orig
+  convert $orig_file -rotate 180 $orig_file.new || die "Failed to rotate $orig_file."
+  mv -f $orig_file.new $orig_file               || die "Failed to move $orig_file.new into place."
   ;;
 "-h")
-  run convert $orig -flop $orig.new
-  run mv -f $orig.new $orig
+  convert $orig_file -flop $orig_file.new  || die "Failed to rotate $orig_file."
+  mv -f $orig_file.new $orig_file          || die "Failed to move $orig_file.new into place."
   ;;
 "-v")
-  run convert $orig -flip $orig.new
-  run mv -f $orig.new $orig
+  convert $orig_file -flip $orig_file.new  || die "Failed to rotate $orig_file."
+  mv -f $orig_file.new $orig_file          || die "Failed to move $orig_file.new into place."
   ;;
 esac
 
 # Update size and clear "transferred" bit in database.
-size=`script/jpegsize $orig | sed "s/.*: //"`
-w=`echo $size | sed "s/ .*//"`
-h=`echo $size | sed "s/.* //"`
-run_mysql "UPDATE images SET transferred=TRUE, width=$w, height=$h WHERE id=$id"
+size=$( $app_root/script/jpegsize $orig_file )
+w=$( echo $size | sed "s/ .*//" )
+h=$( echo $size | sed "s/.* //" )
+run_mysql "UPDATE images SET transferred=TRUE, width=$w, height=$h WHERE id=$id" || warn "Failed to update database: $id should be $w x $h."
 
 # Transfer control to process_image.
-exec script/process_image $id jpg 0
+exec $app_root/script/process_image $id jpg 0
